#! /usr/bin/env python
# __author__ = "Parisa Kianmajd"
#__version__ = "1.0.1"
# Converts list of ISA and articulations pairs to CleanTax format

import csv
import sys
import optparse

# Global variables
isa = {}
art = []
data = {}


def p2c(infile):
    # build a dictionary that maps taxonomy ids to According_To column in the original input file
    with open(infile) as infile:
        reader = csv.reader(infile)
        #skip header row
        next(reader, None)
        for line in reader:
            i = line[0].split(".")[0]
            if i not in data:
                data[i] = {}
            data[i] = line[1]
    with sys.stdin as source:
        lines = csv.reader(source)
        #skip header row
        next(lines, None)
        for line in lines:
            if "ISA" in line:
                index = line[-5].split(".")[0]
                if index not in isa:
                    isa[index] = {}
                if line[-5] not in isa[index]:
                    isa[index][line[-5]]= []
                isa[index][line[-5]].append(line[0])
            else:
                if len(line) > 1:
                    art.append([line[0],line[5],line[6]])
    with sys.stdout as cFile:
        for d in isa:
            cFile.write("taxonomy " + d + " " + data[d] + "\n")
            for i in isa[d]:
                line = "(" + i + " "
                for j in isa[d][i]:
                    line = line + j + " "
                line = line [:-1] + ")" + "\n"
                cFile.write(line)
            cFile.write("\n")
        cFile.write("articulation" + "\n")
        for a in art:
            cFile.write("[" + a[0] + " " + a[1] + " " + a[2] + "]" + "\n")


def parse_options():
# parse options
    parser = optparse.OptionParser(usage = "%prog [options]", version = "%prog 0.1")
    parser.add_option("-i","--ifile",type="string",dest="ifile", default=None, help="file")
    (options, args) = parser.parse_args()
    return options, args


# MAIN
if __name__ == '__main__':
    (options,args) = parse_options()
    if options.ifile == None:
        options.ifile = "in.csv"
p2c(options.ifile)