#! /usr/bin/env python
import csv
import taxon_dictionary
import sys
            
data = {} # a nested dictionary to store the taxonomies

with sys.stdin as source:
    reader = csv.reader(source)
    next(reader, None) #skip header row
# build a nested dictionary
    for name, author, rank in reader:
        if author not in data:
            data[author]={}
        if rank not in data[author]:
            data[author][rank]=[]
        data[author][rank].append(name)
with sys.stdout as dest:
    writer = csv.writer(dest)
    writer.writerow(["id", "Name_Simple", "According_To", "Rank"])
#assign identifiers to each entity
    j = 0
    for author, value in data.iteritems():
        j += 1
        i = 1
        numRanks = []
        for rank in value.keys():
            numRanks.append(taxon_dictionary.rank2num.get(rank,(0,0))[0])
        for rank in [k[0] for k in sorted(zip(value.keys(), numRanks), key=lambda l: l[1])]:
            for name in sorted(value[rank]):
                writer.writerow((str(j) + "." + str(taxon_dictionary.rank2num.get(rank,(0,0))[1]) + str(i), name, author, rank))
                i += 1
