#! /usr/bin/env python

import sys
import yaml
from random import randint

def add_edge(s,t,label):
        edge = {}
        edge.update({"s" : s})
        edge.update({"t" : t})
        edge.update({"label" : label})
        edges.update({s + "_" + t : edge})
def add_node(concept, group):
        node = {}
        node.update({"concept": concept})
        node.update({"group": group})
        node.update({"name": "test" + str(randint(0,100))})
        if group!="(+)":
            nodes.update({group + "." + concept: node})
        else:
            nodes.update({concept: node})
# Main
nodes = {}
edges = {}
art2symbol = {"equals":"==",
                  "is_included_in":"<",
                  "includes":">",
                  "overlaps":"><",
              "disjoint":"!"}
art = []
dictionary = {}  # group number and list of nodes in the group
f = sys.stdin
for line in f.readlines():
    if line.startswith("taxonomy"):
       groups = []
       g = line.split(" ")[1]
    if line.startswith("("):
        groups.append(line[1:-2].split(" "))
    if line ==  "\n":
            dictionary.update({g : groups})
    if line.startswith("["):
        art.append (line[1:-2])
for key, attr in dictionary.iteritems():
    for value in attr:    
            parent = value.pop(0)
            add_node(parent, key)
            for v in value:
                add_node(v, key)
                add_edge(key + "." + v, key + "." + parent, "isa")
for a in art:
    a = a.replace("3sum", "sum")
    a = a.replace ("4sum", "sum")
    a = a.replace("3diff", "diff")
    a = a.replace ("4diff", "diff")
    if "{" in a:
        start = a.split(" {")[0]
        end = a.split("} ")[-1]
        ops = a.split("{", 1)[1].split("}")[0].split(" ")
        label = art2symbol.get(ops[0], ops[0])
        for i in range(1,len(ops)):
        	label = label + " OR " + art2symbol.get(ops[i], ops[i])
        add_edge(start, end, label)
    else:
        if any(l in a for l in ["lsum", "ldiff"]):
            if "lsum" in a:
                    l = "lsum"
                    op = "+"
            else:
                    l = "ldiff"
                    op = "-"
            plus = a.split(l + " ")[-1].replace(".","") + op
            add_node(plus, "(+)")
            add_edge(plus, a.split(" " + l + " ")[-1], "out")
            for i in range(0,len(a.split(" " + l)[0].split(" "))):
                add_edge(a.split(" " + l)[0].split(" ")[i], plus, "in")
        elif any(l in a for l in ["rsum", "rdiff"]):
            if "rsum" in a:
                    l = "rsum"
                    op = "+"
            else:
                    l= "rdiff"
                    op = "-"
            plus = a.split(" " + l)[0].replace(".","") + op
            add_node(plus, "(+)")
            add_edge(plus, a.split(" " + l + " ")[0], "out")
            for i in range(1,len(a.split(" " + l)[-1].split(" "))):
                add_edge(a.split(" " + l)[-1].split(" ")[i], plus,"in")
        else:
                add_edge(a.split(" ")[0], a.split(" ")[2], art2symbol.get(a.split(" ")[1], a.split(" ")[1]))
f.close()
with sys.stdout as outfile:
   outfile.write(yaml.safe_dump(nodes, default_flow_style=False))
   outfile.write(yaml.safe_dump(edges, default_flow_style=False))