#! /usr/bin/env python
# __author__ = "Parisa Kianmajd"
#__version__ = "1.0.1"
# convert the suggested ISA pairs to cleanTax format
# which can later be visualized by Euler visualizer

import csv
import sys
import taxon_dictionary

def main (iFile, oFile):           
            
    data = {} 

    inputData = csv.DictReader(iFile) 

    for row in inputData:
	gId = row["ID2"].split(".")[0]
        if row["ID2"] not in data:
            data[row["ID2"]] = []
        data[row["ID2"]].append(row["ID1"])
        
    with oFile:
        oFile.write("taxonomy " + gId  + " Taxonomy" + gId  + "\n")
        for i in data:
            line = "(" + i + " "
            for j in data[i]:
                line = line + j + " "
            line = line [:-1] + ")" + "\n"
            oFile.write(line)

# MAIN
if __name__ == '__main__':
    main(sys.stdin, sys.stdout)

