#!/usr/bin/env python
import sys
import sets

lines_seen = sets.Set()
try:
    while True:
        line = raw_input()
        if line not in lines_seen:
            lines_seen.add(line)
            print line
            sys.stdout.flush()
except EOFError:
    sys.stdout.flush()
