#! /usr/bin/env python

import csv
import sys
import dictionary

data = {}

with sys.stdin as source:
    lines = csv.reader(source)
    next(lines, None) #skip header row
    # categorize the lines based on the first 3 letters of the name
    for line in lines:
        if line[1][0:3] not in data:
            data[line[1][0:3]]= []
        data[line[1][0:3]].append(line)

# compare the items in the list two by two
with sys.stdout as dest:
    writer = csv.writer(dest)
    writer.writerow(["id", "Name_Simple", "According_To", "Rank", "Suggested ISA Pairs", "Suggested Articulation Pairs"])
    for d in data:
        for i in data[d]:
            art = []
            isa = []
            for j in data[d]:
                if i!=j:
                    if i[2]!=j[2]:
                        art.append([j[0],j[1]])
                    else:
                        rank1 = dictionary.rank2num.get(i[3],(0,0))[0]
                        rank2 = dictionary.rank2num.get(j[3],(0,0))[0] 
                        if isa == [] and rank1 > rank2:
                            isa.append([j[0],j[1]])
            i.append(isa)
            i.append(art)
            writer.writerow(i)

with open("pairs.csv", 'wb') as pairs:
    writer = csv.writer(pairs)
    writer.writerow(["id", "Name", "Relationship", "id", "Name"])
    for d in data:
        for i in data[d]:
            for p in i[4]:
               writer.writerow([i[0], i[1] , "ISA", p[0],p[1]])
            for a in i[5]:
               writer.writerow([i[0], i[1], " ", a[0],a[1]])