#! /usr/bin/env python

import sys
import yaml
import optparse
from collections import defaultdict

nodes = defaultdict(list)
edges = defaultdict(list)
wList = []
# parse the stylesheet file
def scale(value, dMin, dMax, sMin, sMax):
    # Find how 'wide' each range is
    dSpan = dMax - dMin
    sSpan = sMax - sMin
    # Convert the range in data file into a 0-1 range (float)
    if dSpan != 0:
    	scaledValue = float(value - dMin) / float(dSpan)
    else:
    	scaledValue = 0
    # Convert the 0-1 range into a value in the stylesheet range
    return sMin + (scaledValue * sSpan)
def read_stylesheet(stylefile):
    global styles
    with open(stylefile) as style_file:    
        styles = yaml.load(style_file)          
def apply_style(data_file, f):
    f.write("digraph{\n")
    f.write(str(styles["graphstyle"]["graph"]))
    with data_file: 
        data = yaml.load(data_file)
    #separate nodes from edges
        for key, value in data.iteritems():
            if "group" in data[key]:
                nodes[data[key]["group"]].append(data[key]["concept"])
            elif "label" in data[key]:
                if "w" in data[key]:
                    wList.append(data[key]["w"])
                else:
                    wList.append("1")
                if not any(d["label"] == value["label"] for d in styles["edgestyle"]):
                    edges["default"].append(value.items())
                else:
                    edges[data[key]["label"]].append(value.items())
    glabel = '<TR> <TD COLSPAN="2"><B>Nodes</B></TD> </TR> \n' 
    for g in nodes:
        glabel = glabel + "<TR> \n <TD>" + g + "</TD> \n <TD>" + str(len(nodes[g])) + "</TD> \n </TR> \n"
    # if the style is not defined use the default
        if (styles["graphstyle"]["subgraph"] == "on" and g!="none"):
            f.write("subgraph cluster" + g + '{ style=invis\n')
        if g in styles["nodestyle"]:
            group = g
        else:
            group = "default"
        f.write("node[" + styles["nodestyle"][group] + '] \n')
        for n in nodes[g]:
            if (g!= "common" and g!= "none"):
               f.write('"'+ g + "." + n + '"\n')
            else:
                f.write('"'+ n + '"')
                if "+" in n:
                    f.write(' [label="+"]')
                elif "-" in n:
                    f.write(' [label="-"]')
                f.write("\n")
        if (styles["graphstyle"]["subgraph"] == "on" and g != "none"):
            f.write("}\n")
    glabel = glabel + '<TR> <TD COLSPAN="2"><B>Edges</B></TD> </TR> \n'  
    for l in edges:
        style = (item for item in styles["edgestyle"] if item["label"] == l).next()
        f.write("edge["+ style["dot"] +"]\n")
        glabel = glabel + "<TR> \n <TD>" + l + "</TD> \n <TD>" + str(len(edges[l])) + "</TD> \n </TR> \n"
        for e in edges[l]:
            if e[2][1] == ">":
                f.write('"' + e[1][1] + '" -> "' + e[0][1] + '"')
                f.write(' [dir= back]')
            else:
                f.write('"' + e[0][1] + '" -> "' + e[1][1] + '"')
            if style["display"] == "(w)penwidth":
                if styles["graphstyle"]["wmap"] == "on":
                	w = e[2][1]
                	if not "w" in (item[0] for item in e):
                            w = "1"
                	w = str(scale(int(w), int(min(wList)), int(max(wList)), int(styles["graphstyle"]["wmin"]), int(styles["graphstyle"]["wmax"])))              	
                f.write('[penwidth=' + w + "]")
        # check options for displaying label
            elif style["display"] == "(w)display":
                f.write(' [label="' + e[2][1] + '"]')
            elif (style["display"] == "label"):
                f.write(' [label="' + e[-1][1] + '"]')
            else:
                f.write(' [label="' + style["display"] + '"]')
            f.write("\n")
    if styles["graphstyle"]["legend"] == "on":
        f.write('{rank = sink Legend [fillcolor= white margin=0 label=< <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="4"> \n' )
        f.write(glabel)
        f.write("</TABLE> \n >] }")
    f.write("}")            
    f.close()
def parse_options():
	# parse options
	parser = optparse.OptionParser(usage = "%prog [options]", version = "%prog 0.1")
	parser.add_option("-s","--sfile",type="string",dest="sfile",
					  default=None,
					  help="file")
	(options,args) = parser.parse_args()
	return (options,args)

# MAIN 
if __name__ == '__main__':
	(options,args) = parse_options()
	if options.sfile == None:
		options.sfile = "inputstyle.yaml"
	read_stylesheet(options.sfile)
	apply_style(sys.stdin, sys.stdout)