#! /usr/bin/env python2
# __author__ = "Parisa Kianmajd"
#__version__ = "1.0.1"
# input: a MIR csv file
# output: a csv file with three columns <Name, Author, Rank>

# Copyright (c) 2014 University of California, Davis
# 
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import csv
import sys
genus = list()

def findRank(e):
    if len(e.split('_')) == 3:
           return 'Subspecies'
    if len(e.split('_')) == 2:
        return 'Species'
    if len(e.split('_')) == 1:
        if e.endswith('inae'):
            return 'Subfamily'
        if e.endswith('idae'):
            return 'Family'
        if e.endswith('oidea'):
            return 'Superfamily'
        if e in genus:
            return 'Genus'
        return '?'
 
if __name__ == '__main__':
    data = dict()
    inputData = csv.reader(sys.stdin)
    for line in inputData:
        for a in [line[0],line[2]]:
            g = a.split(".")[0]
            e = a.split(".")[1]
            if g not in data:
                data[g] = list()
            if e not in data[g]:
                data[g].append(e)
                if "_" in e:
                    genus.append(e.split("_")[0])
    writer = csv.writer(sys.stdout)
    writer.writerow(['Name', 'Year', 'Rank']) 
    for g in data:
        for e in data[g]:
            rank = findRank(e)
            writer.writerow([e, g ,rank]) 
