#! /usr/bin/env python2
# __author__ = "Parisa Kianmajd"
#__version__ = "1.0.1"
# Converts list of ISA and articulations pairs to CleanTax format

# Copyright (c) 2014 University of California, Davis
# 
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import csv
import sys
import wizardParser

# Global variables
isa = {}
art = []
data = {}

def main(iFile,tFile):
    reader = []
    lines = []
    # build a dictionary that maps taxonomy ids to According_To column in the original input file
    if tFile != " ":
        for f in tFile:
            reader += csv.DictReader(open(f))
        for line in reader:
            i = line["ID"].split(".")[0]
            if i not in data:
                data[i] = {}
            data[i] = line["Author"]
    for f in iFile:
        lines += csv.DictReader(open(f))
    for line in lines:
        if line["Relation"] == "ISA":
            index = line["ID2"].split(".")[0]
            if index not in isa:
                isa[index] = {}
            if line["ID2"].split(".")[1] not in isa[index]:
                isa[index][line["ID2"].split(".")[1]]= []
            isa[index][line["ID2"].split(".")[1]].append(line["ID1"].split(".")[1])
        else:
            if len(line) > 1:
                art.append([line["ID1"],line["Relation"],line["ID2"]])
    with sys.stdout as cFile:
        for d in isa:
            if tFile != " ":
                name = data[d]
            else:
                name = "Taxonomy" + d
            cFile.write("taxonomy " + d + " " + name + "\n")
            for i in isa[d]:
                line = "(" + i + " "
                for j in isa[d][i]:
                    line = line + j + " "
                line = line [:-1] + ")" + "\n"
                cFile.write(line)
            cFile.write("\n")
        if len(art) != 0:
            cFile.write("articulation" + "\n")
            for a in art:
                cFile.write("[" + a[0] + " " + a[1] + " " + a[2] + "]" + "\n")


# MAIN
if __name__ == '__main__':
    main(wizardParser.args.iFile, wizardParser.args.tFile)
